// src/core/use-modal.tsx
import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useClickOutside } from '../hooks/use-click-outside.js';
import { useDialogKeydown } from '../hooks/use-dialog-keydown.js';
import { useDialogLifecycle } from '../hooks/use-dialog-lifecycle.js';
import { useFocusManagement } from '../hooks/use-focus-management.js';
import { useDialogManagerContext } from '../manager/dialog-manager-context.js';
import { getDialogAnimationStyles } from '../utils/animation-utils.js';
import { canDismiss } from '../utils/dismiss-gate.js';
import { Key } from '../utils/keys.js';
import { createLogger } from '../utils/logger.js';
import { finalizeModalClose } from './finalize-close.js';
import { createModalStore } from './modal-store.js';
import { dialogPlacement } from './placement.js';
import { useModalOutletContext } from './modal-outlet.js';
import { createActionEngine } from '../actions/action-engine.js';
import { formatHotkeyLabel } from '../utils/hotkey-utils.js';
import type { ActionCloseFn, ActionFactory } from '../actions/types.js';
import type { OpenRequestDispatch } from '../manager/dialog-manager.js';
import type {
  GetDialog,
  ModalAnimation,
  ModalHandle,
  UseModalOptions,
  UseModalReturn,
  AwaitedClose,
} from './types.js';

/**
 * What an action does when it is given no handler: close with its own reason.
 *
 * Typed at `never` rather than at the modal's payload, which is what makes it usable as the
 * default for every action — a handler that ignores its `close` argument fits any payload.
 */
const autoClose: (close: ActionCloseFn) => void = (close) => {
  close();
};

const log = createLogger('modal');

const defaultAnimation: ModalAnimation = {
  entrance: { opacity: 1, transform: 'scale(1)' },
  exit: { opacity: 0, transform: 'scale(0.95)' },
  duration: 200,
  exitDuration: 150,
  transitionProperty: 'opacity, transform',
};

// ── useModal Hook ───────────────────────────────────────────────────────────

/**
 * Core modal hook that renders a native `<dialog>` element with animation,
 * backdrop handling, and typed close results.
 *
 * Actions are declared by being rendered: the `action` given to `render` names a reason, binds
 * a handler and returns the props for its button, all in one expression. There is no action
 * config and nothing to pass in.
 *
 * @typeParam TData - Type of the close data payload. Defaults to `void`.
 * @typeParam TReason - The reasons this modal closes with. Left at `string` any reason is
 * accepted; declaring a union (`useModal<Result, 'save' | 'cancel'>`) rejects a mistyped
 * reason, autocompletes it, and makes a `switch` on `result.reason` in `onClose` exhaustive.
 * `'dismiss'` is always allowed — the library produces it on Escape, backdrop click and
 * teardown.
 *
 * @example
 * const { openAndWait, Modal } = useModal<void, 'ok'>({
 *   id: 'my-modal',
 *   render: ({ action }) => <button {...action('ok')}>OK</button>,
 *   onClose: (result) => console.log(result.reason),
 * });
 */
export function useModal<TData = void, TReason extends string = string>(
  options: UseModalOptions<TData, TReason>
): UseModalReturn<TData, TReason> {
  const {
    id: modalId,
    render,
    animation: animationProp,
    style: styleProp,
    dismissKey: dismissKeyProp,
    dismissWhilePreparing: dismissWhilePreparingProp,
    onKeyDown,
    prepare,
    onOpenRequest,
    onClose,
    modalType,
    nonModal,
    portal,
    clipContainer,
    ariaLabel,
    ariaLabelledBy,
    ariaDescribedBy,
    role,
  } = options;
  // dismissOnBackdropClick only exists in the modal variant (nonModal !== true)
  const dismissOnBackdropClick =
    options.nonModal !== true ? options.dismissOnBackdropClick : undefined;
  // dismissOnClickOutside only exists in the non-modal variant (nonModal === true)
  const dismissOnClickOutside =
    options.nonModal === true ? (options.dismissOnClickOutside ?? false) : false;

  const isNonModal = nonModal ?? false;
  const shouldPortal = portal ?? false;
  // Where this dialog is positioned from, and what it has to be positioned *against*. The
  // rules — and why a contained dialog needs a host at all — live in `core/placement.ts`,
  // framework-free, so a second binding places a dialog exactly the way this one does.
  const placement = dialogPlacement({
    nonModal: isNonModal,
    portal: shouldPortal,
    clip: clipContainer ?? false,
  });
  const dismissWhilePreparing = dismissWhilePreparingProp ?? true;
  const dm = useDialogManagerContext();

  // Everything here closes over `store` alone, so it is all built once and keeps a
  // stable identity for the lifetime of the hook. That matters for the returned
  // `open` / `openAndWait` / `handle`: a fresh function each render would force
  // consumers to shuttle them through refs to use them in effects or pass them to
  // memoized children (and would defeat memoization inside `render`, which receives
  // `handle`). React Compiler cannot memoize them for us — they capture a value it
  // treats as opaque — so we hoist them into the initializer instead.
  const [init] = useState(() => {
    const store = createModalStore<TData, TReason>(modalId);
    // Built here rather than handed in, so it can be wired straight to this modal's `close`.
    // Nothing has to bridge the two because nothing built it anywhere else.
    const engine = createActionEngine<TData, TReason>(modalId);
    engine.bindClose((reason, data) => {
      store.close(reason, data);
    });

    // Stable getter that reads dialogRef.current — safe to pass to hooks
    // because the closure captures the ref but doesn't access .current during render.
    const getDialog: GetDialog = () => {
      return dialogRef.current;
    };

    // The store decides which branch settles the promise (start / join an in-flight
    // open / resolve immediately) — it owns the state machine, so it owns the rule.
    const open = (): Promise<void> => {
      return new Promise((resolve) => {
        store.beginOpen(resolve);
      });
    };

    // The resolver goes on **before** the open is requested, and that ordering is the whole
    // method — it is why the store's `addCloseResolver` is not public. A close resolver waits
    // for the *next* close by design, so one registered afterwards waits for a close that will
    // never come; `prepare` is what makes that window wide enough to fall into, since
    // `finalize` flushes the open resolvers defensively and an `open()` would return as if
    // nothing had happened. Pinned by `modal-store.test.ts` and by `open-and-wait.story.tsx`.
    const openAndWait = (): Promise<AwaitedClose<TData, TReason>> => {
      const closed = new Promise<AwaitedClose<TData, TReason>>((resolve) => {
        store.addCloseResolver(resolve);
      });
      store.beginOpen();
      return closed;
    };

    const handle: ModalHandle<TData, TReason> = {
      close: (reason = 'dismiss', data?: TData) => {
        store.close(reason, data);
      },
    };

    return { store, engine, getDialog, open, openAndWait, handle };
  });
  const { store, engine, getDialog, open, openAndWait, handle } = init;
  const snap = useSyncExternalStore(store.subscribe, store.getSnapshot);
  const actionSnap = useSyncExternalStore(engine.subscribe, engine.getSnapshot);

  /**
   * The factory handed to `render`. Calling it declares the action — that is the only place an
   * action is ever declared — and returns the props for its button.
   */
  const action: ActionFactory<TData, TReason> = (reason, handlerOrOptions) => {
    const opts = typeof handlerOrOptions === 'function' ? undefined : handlerOrOptions;
    const handler = typeof handlerOrOptions === 'function' ? handlerOrOptions : opts?.onAction;
    const effective = handler ?? autoClose;
    const onClickBefore = opts?.onClick;
    const hotkey = opts?.hotkey;

    engine.declare(reason, hotkey);
    const state = engine.stateOf(reason);

    return {
      type: opts?.type ?? 'button',
      onClick: async (event) => {
        // The caller's handler goes first and owns the veto, so composing a click never has to
        // mean replacing the action's. Same protocol as `onKeyDown`.
        onClickBefore?.(event);
        if (event.defaultPrevented) {
          return;
        }
        await engine.run(reason, effective);
      },
      'data-loading': state.isRunning,
      // Includes *this* action: a running button that stays clickable re-enters its own handler
      // on a double click, which for a submit means submitting twice.
      disabled: actionSnap.hasRunningAction || (opts?.disabled ?? false),
      'aria-busy': state.isRunning,
      ...(hotkey !== undefined && { 'aria-keyshortcuts': formatHotkeyLabel(hotkey) }),
      ...(opts?.focusOnOpen === true && { 'data-focus-on-open': true }),
    };
  };

  const dialogRef = useRef<HTMLDialogElement>(null);
  const animation = animationProp ?? defaultAnimation;

  // Intentionally no deps array — runs every render to always capture the latest onClose
  // reference without needing a ref. Extracted hooks and unmount cleanup read it via the store.
  useEffect(() => {
    store.setOnClose(onClose);
  });

  // ── Extracted hooks ──────────────────────────────────────────────────────

  // Resolve the effective dismiss key (defaults to Escape when not specified)
  const dismissKey = dismissKeyProp ?? Key.Escape;

  const hookCtx = { store, getDialog, modalId, phase: snap.phase, dm };

  useDialogLifecycle(hookCtx, { prepare, animation, nonModal: isNonModal });

  useDialogKeydown(hookCtx, {
    isPreparing: snap.isPreparing,
    onKeyDown,
    dismissKey,
    engine,
    nonModal: isNonModal,
    dismissWhilePreparing,
  });

  useFocusManagement(hookCtx, { engine });

  useClickOutside(hookCtx, {
    dismissOnClickOutside,
    dismissWhilePreparing,
    engine,
  });

  // ── Registry registration + teardown ────────────────────────────────────
  // Re-runs when the reported flags (`modalType` / `nonModal`) change, because those
  // change the rendered DOM structure (inline / portal / contained wrapper) and a native
  // <dialog> cannot survive being remounted into a different structure while open. The
  // cleanup therefore both unregisters AND finalizes an open modal: on a structural prop
  // change this closes it cleanly (rather than leaving a stuck, orphaned dialog), and on a
  // true unmount it settles `onClose` and any pending close resolver with a 'dismiss' reason.
  // The handler the registry holds is stable for the life of the registration, and reads the
  // latest one through a ref — a new closure every render would make this effect re-register on
  // every render, and re-registering is not free: it tears the subscription down and back up.
  const openRequestHandler = useRef(onOpenRequest);
  useEffect(() => {
    openRequestHandler.current = onOpenRequest;
  }, [onOpenRequest]);

  // Whether the dialog answers bridged opens at all is a registration-time fact, so it is a
  // dependency below: a dialog that starts declaring one has to re-register to become reachable.
  const acceptsOpenRequests = onOpenRequest !== undefined;

  useEffect(() => {
    dm.register(modalId, store, {
      modalType: modalType ?? 'modal',
      nonModal: isNonModal,
      ...(acceptsOpenRequests && {
        // Returned, not swallowed: the manager awaits the handler, so an owner that validates
        // asynchronously still gets to refuse before `requestOpenAndWait` answers.
        onOpenRequest: (payload: unknown, request: OpenRequestDispatch) => {
          return openRequestHandler.current?.(payload, request);
        },
      }),
    });

    return () => {
      const wasOpen = store.getSnapshot().phase !== 'closed';

      dm.unregister(modalId);

      if (wasOpen) {
        log('Tearing down open modal', { id: modalId });

        // If not already closing, initiate close with 'dismiss' reason so closeResult is
        // set for both onClose and the close resolvers (this also cancels any pending open frame).
        // If already closing, this is a no-op and closeResult retains the original reason.
        store.close('dismiss');

        finalizeModalClose(store, getDialog(), (error) => {
          log.error('onClose callback failed during cleanup', {
            id: modalId,
            error: error.message,
          });
        });
      }

      // Unconditional: a modal can be destroyed while closed and still have waiters, because
      // A close resolver may be registered before the first open — or after a close, awaiting
      // the next one that now never comes. `finalizeModalClose` above already settled the
      // open-modal case, so this drains an empty queue there and only bites in the case it
      // exists for. Without it those promises never settle.
      store.abandon();
    };
    // `shouldPortal` is a dep (though unused in the body) because it, like `nonModal`,
    // changes the rendered structure — so toggling it while open must tear the modal down
    // too, otherwise the remounted-into-a-new-structure <dialog> is left stuck open.
  }, [acceptsOpenRequests, dm, getDialog, isNonModal, modalId, modalType, shouldPortal, store]);

  // ── Backdrop click ──────────────────────────────────────────────────────

  // Inline backdrop click handler to satisfy React Compiler
  const handleBackdropClick = (event: React.MouseEvent<HTMLDialogElement>) => {
    // Non-modal dialogs have no backdrop — skip click-outside detection
    if (isNonModal) {
      return;
    }

    // Backdrop dismissal is opt-out without actions, opt-in with them.
    if (!(dismissOnBackdropClick ?? !engine.hasActions())) {
      return;
    }

    if (
      !canDismiss({
        phase: snap.phase,
        isPreparing: snap.isPreparing,
        dismissWhilePreparing,
        hasRunningAction: actionSnap.hasRunningAction,
      })
    ) {
      return;
    }

    // A real backdrop click targets the <dialog> itself; anything originating in the
    // content bubbles up with a descendant as its target. Checking this first is what
    // makes the coordinate test below safe: a keyboard-activated button dispatches a
    // click with clientX/clientY of 0, which lies outside a centred dialog's rect and
    // would otherwise read as a backdrop click and dismiss the modal.
    if (event.target !== event.currentTarget) {
      return;
    }

    const dialog = dialogRef.current;
    if (!dialog) {
      return;
    }

    // The dialog's own box can extend past its content (padding, a template's sizing),
    // so confirm the pointer actually landed outside it before dismissing.
    const rect = dialog.getBoundingClientRect();
    const isOutside =
      event.clientX < rect.left ||
      event.clientX > rect.right ||
      event.clientY < rect.top ||
      event.clientY > rect.bottom;

    if (isOutside) {
      store.close('dismiss');
    }
  };

  // ── Outlet-aware rendering ──────────────────────────────────────────────

  const outlet = useModalOutletContext();

  /**
   * Runs the caller's `render` inside a declaration window, so the engine learns exactly which
   * actions this pass drew. Re-declaring per pass (rather than accumulating) is what keeps a
   * hotkey from outliving the button that owned it and going on suppressing the dismiss key.
   */
  const renderContent = () => {
    engine.beginRender();
    try {
      return render({
        isPreparing: snap.isPreparing,
        handle,
        action,
        hasRunningAction: actionSnap.hasRunningAction,
        error: actionSnap.error,
      });
    } finally {
      engine.endRender();
    }
  };

  const dialogElement = (
    <dialog
      ref={dialogRef}
      // The styling surface: `data-modal-id` is this modal's id and `data-modal-type` its
      // variant, so user-land CSS can reach one dialog (or every non-modal one) without
      // knowing anything about the tree it renders in — and without keying off a test id.
      data-modal-id={modalId}
      data-testid={`modal-${modalId}`}
      data-modal-type={isNonModal ? 'non-modal' : 'modal'}
      // The name and the role are the caller's: nothing here knows what this dialog is for.
      // Omitted rather than defaulted when absent, so a `<dialog>` keeps its own implicit role
      // and an unnamed one is visibly unnamed to an audit instead of quietly `aria-label=""`.
      aria-label={ariaLabel}
      aria-labelledby={ariaLabelledBy}
      aria-describedby={ariaDescribedBy}
      role={role}
      onClick={handleBackdropClick}
      style={getDialogAnimationStyles(snap.phase, animation, styleProp, placement)}
    >
      {/*
        Content wrapper. It deliberately does NOT stop click propagation: the backdrop
        handler above identifies a real backdrop click by its target, so swallowing
        content clicks here would only rob user-land ancestors of events they should see.
      */}
      <div style={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' }}>
        {snap.phase !== 'closed' && renderContent()}
      </div>
    </dialog>
  );

  let dialogNode: ReactNode;

  if (shouldPortal) {
    dialogNode = createPortal(dialogElement, document.body);
  } else if (placement.host) {
    // The host `dialogPlacement` asked for: the dialog's `absolute` positioning resolves
    // against this element (the closest positioned ancestor always wins), immune to
    // transformed ancestors above it. It fills its parent, so a slide anchors to that region.
    dialogNode = (
      <div data-modal-container={modalId} style={placement.host}>
        {dialogElement}
      </div>
    );
  } else {
    dialogNode = dialogElement;
  }

  // Register/update outlet content — NO cleanup. The <dialog> is always mounted so
  // dialogNode is never null, and we never need to unregister mid-lifecycle.
  // Cleanup on unmount is handled by the effect below.
  //
  // Passive, not layout. A layout effect looks tempting here — the node is rendered by
  // the outlet rather than by us, so in principle the outlet must re-render before the
  // paint or that paint shows the previous node. Measured, that frame does not exist:
  // React flushes the passive effect and the outlet's cascading re-render before the
  // next animation frame, and a layout effect is not even synchronous through the
  // cascade (the DOM still reads the old value at the end of the click's own task
  // either way). Both variants are indistinguishable by the next frame, so this stays
  // passive and does not block paint. See the paint-timing test in __tests__.
  useEffect(() => {
    if (!outlet) {
      return;
    }
    outlet.register(modalId, dialogNode);
  });

  // Unmount-only cleanup: unregister when the component unmounts or the
  // outlet/modalId identity changes (both are stable in practice).
  useEffect(() => {
    if (!outlet) {
      return;
    }
    return () => {
      outlet.unregister(modalId);
    };
  }, [modalId, outlet]);

  const Modal: ReactNode = outlet ? null : dialogNode;

  return {
    open,
    isVisible: snap.phase !== 'closed',
    isPreparing: snap.isPreparing,
    Modal,
    openAndWait,
    handle,
    action,
    hasRunningAction: actionSnap.hasRunningAction,
    error: actionSnap.error,
    dialogManager: dm,
  };
}

// src/solid/use-modal.ts
import { createEffect, createMemo, createRenderEffect, getOwner, onCleanup } from 'solid-js';
import { insert } from 'solid-js/web';
import type { JSX } from 'solid-js';
import { createActionFactory } from '../core/action-factory.js';
import { attachClickOutside } from '../core/attach-click-outside.js';
import { createFocusCoordinator } from '../core/attach-focus.js';
import {
  attachDialogCancel,
  attachDialogKeydown,
  attachWindowDismissKey,
} from '../core/attach-keydown.js';
import { openSequence, syncCloseSequence } from '../core/attach-lifecycle.js';
import { DIALOG_CONTENT_STYLE, dialogAttributes } from '../core/dialog-props.js';
import {
  createModalRuntime,
  resolveModalConfig,
  shouldDismissOnBackdropClick,
  teardownModal,
} from '../core/modal-runtime.js';
import { applyStyle } from '../core/style.js';
import {
  DEFAULT_MODAL_ANIMATION,
  getDialogAnimationStyles,
  resolveAnimation,
} from '../utils/animation-utils.js';
import { useDialogManagerContext } from './dialog-manager-context.js';
import { fromStore } from './from-store.js';
import { useModalOutletContext } from './modal-outlet.js';
import type { ModalDomContext } from '../core/attach-types.js';
import type { DialogStyle } from '../core/style.js';
import type { GetDialog, ModalRenderArgs } from '../core/types.js';
import type { ModalAnimation, UseModalOptions, UseModalReturn } from './types.js';

/**
 * `umbra/solid`'s core hook — the same `useModal` as React's, over the same core.
 *
 * **Written without JSX, on purpose.** Solid's JSX is a compile step (`babel-preset-solid`), and
 * requiring it to build *the library* would put a second toolchain in the way of a package whose
 * whole claim is that a binding is thin. So the binding builds its one `<dialog>` with
 * `document.createElement` and Solid's own `insert` — which is precisely what compiled JSX emits.
 * Consumers write ordinary Solid JSX; their compiler handles it, and what crosses the boundary is
 * a `JSX.Element`, which needs no agreement about tooling.
 *
 * The differences from React's binding are the two that follow from the renderer, and no others:
 *
 * - **Nothing re-renders.** The body runs once. Everything live is a getter over a signal, so
 *   `modal.isVisible` inside JSX subscribes that one expression and nothing else.
 * - **An action un-declares itself.** React expires a declaration by re-running `render`
 *   wholesale; here a button removed by its own `<Show>` calls `engine.undeclare` from
 *   `onCleanup`. Without it the hotkey outlives the button and `hasActions()` — which decides
 *   whether a backdrop click dismisses — never goes back to false.
 *
 * @typeParam TData - Type of the close data payload. Defaults to `void`.
 * @typeParam TReason - The reasons this modal closes with. Declare them.
 */
export function useModal<TData = void, TReason extends string = string>(
  options: UseModalOptions<TData, TReason>
): UseModalReturn<TData, TReason> {
  const modalId = options.id;

  // The defaults and the variant narrowing, from the one place both bindings read them.
  const {
    isNonModal,
    shouldPortal,
    dismissOnBackdropClick,
    dismissOnClickOutside,
    dismissWhilePreparing,
    dismissKey,
    modalType,
    placement,
  } = resolveModalConfig(options);

  // Annotated for the reason React's binding gives: an un-annotated fallback leaves a union
  // whose branches disagree about the style parameter `getDialogAnimationStyles` infers.
  const animation: ModalAnimation = options.animation ?? DEFAULT_MODAL_ANIMATION;

  const dm = useDialogManagerContext();

  const { store, engine, open, openAndWait, handle } = createModalRuntime<TData, TReason>(modalId);

  const snapshot = fromStore(store);
  const actionState = fromStore(engine);

  // ── The element ─────────────────────────────────────────────────────────────
  //
  // Built here rather than described and handed to a renderer, which is what removes the ref
  // dance the React binding needs: `getDialog` can simply close over it.

  const dialog = document.createElement('dialog');
  const getDialog: GetDialog = () => {
    return dialog;
  };

  for (const [name, value] of Object.entries(
    dialogAttributes({
      modalId,
      nonModal: isNonModal,
      ariaLabel: options.ariaLabel,
      ariaLabelledBy: options.ariaLabelledBy,
      ariaDescribedBy: options.ariaDescribedBy,
      role: options.role,
    })
  )) {
    // Omitted rather than emptied when absent — an unnamed dialog stays visibly unnamed to an
    // audit instead of quietly carrying `aria-label=""`.
    if (value !== undefined) {
      dialog.setAttribute(name, value);
    }
  }

  const content = document.createElement('div');
  applyStyle(content, DIALOG_CONTENT_STYLE);
  dialog.append(content);

  // The dialog's own styles, recomputed per phase. A render effect rather than an effect, so the
  // exit/entrance state is written before `openSequence` shows the dialog in the same flush.
  let appliedStyle: DialogStyle | undefined;
  createRenderEffect(() => {
    appliedStyle = applyStyle(
      dialog,
      getDialogAnimationStyles(snapshot().phase, animation, options.style, placement),
      appliedStyle
    );
  });

  // The host `dialogPlacement` asked for, when it asked for one: the dialog's `absolute`
  // positioning resolves against it, immune to a transformed ancestor above.
  let placed: HTMLElement = dialog;
  if (placement.host) {
    const host = document.createElement('div');
    host.setAttribute('data-modal-container', modalId);
    applyStyle(host, placement.host);
    host.append(dialog);
    placed = host;
  }

  const baseAction = createActionFactory(engine, actionState);

  /**
   * The core factory plus the one thing a fine-grained renderer owes it: an expiry.
   *
   * The owner here is whatever scope drew the button — the modal's content, or the `<Show>`
   * branch it sits in — so a button that disappears takes its declaration with it.
   */
  const action: typeof baseAction = (reason, handlerOrOptions) => {
    const props = baseAction(reason, handlerOrOptions);
    if (getOwner()) {
      onCleanup(() => {
        engine.undeclare(reason);
      });
    }
    return props;
  };

  const isPreparing = () => {
    return snapshot().isPreparing;
  };
  const hasRunningAction = () => {
    return actionState().hasRunningAction;
  };
  const currentError = () => {
    return actionState().error;
  };
  const isVisible = createMemo(() => {
    return snapshot().phase !== 'closed';
  });

  const renderArgs: ModalRenderArgs<TData, TReason> = {
    handle,
    action,
    get isPreparing() {
      return isPreparing();
    },
    get hasRunningAction() {
      return hasRunningAction();
    },
    get error() {
      return currentError();
    },
  };

  // ── Content ─────────────────────────────────────────────────────────────────
  //
  // Keyed on visibility alone, not on the whole snapshot: `isPreparing` reaches the content as a
  // getter, so a modal that starts loading updates the part that reads it instead of redrawing.
  insert(content, () => {
    if (!isVisible()) {
      return null;
    }
    // The declaration window. Actions drawn eagerly land in this pass; ones inside a `<Show>`
    // run later and declare themselves then — `declare` falls back to the live table for exactly
    // that case, and `undeclare` above is what retires them.
    engine.beginRender();
    try {
      return options.render(renderArgs);
    } finally {
      engine.endRender();
    }
  });

  // ── Backdrop click ──────────────────────────────────────────────────────────

  // The decision — variant, opt-in/opt-out, the shared dismissal gate, and the geometry — is
  // `modal-runtime.ts`'s, and it is the same call React's binding makes from its `onClick`.
  dialog.addEventListener('click', (event: MouseEvent) => {
    if (
      shouldDismissOnBackdropClick(event, dialog, {
        store,
        engine,
        isNonModal,
        dismissOnBackdropClick,
        dismissWhilePreparing,
      })
    ) {
      store.close('dismiss');
    }
  });

  // ── Lifecycle ───────────────────────────────────────────────────────────────

  const domContext = (): ModalDomContext => {
    return { store, getDialog, modalId, phase: snapshot().phase, dm };
  };

  createEffect(() => {
    openSequence(domContext(), { prepare: options.prepare, nonModal: isNonModal });
  });

  const { primaryProperty, exitDuration } = resolveAnimation(animation);
  createEffect(() => {
    const teardown = syncCloseSequence(domContext(), {
      nonModal: isNonModal,
      primaryProperty,
      exitDuration,
    });
    if (teardown) {
      onCleanup(teardown);
    }
  });

  createEffect(() => {
    const snap = snapshot();
    const dom: ModalDomContext = { store, getDialog, modalId, phase: snap.phase, dm };
    const keydownOptions = {
      isPreparing: snap.isPreparing,
      onKeyDown: options.onKeyDown,
      dismissKey,
      engine,
      nonModal: isNonModal,
      dismissWhilePreparing,
    };
    const teardowns = [
      attachDialogKeydown(dom, keydownOptions),
      attachDialogCancel(dom, keydownOptions),
      attachWindowDismissKey(dom, keydownOptions),
    ];
    onCleanup(() => {
      for (const teardown of teardowns) {
        teardown?.();
      }
    });
  });

  createEffect(() => {
    const teardown = attachClickOutside(domContext(), {
      dismissOnClickOutside,
      dismissWhilePreparing,
      engine,
    });
    if (teardown) {
      onCleanup(teardown);
    }
  });

  const focus = createFocusCoordinator({ getDialog }, { engine });
  createEffect(() => {
    const teardown = focus.sync(snapshot().phase);
    if (teardown) {
      onCleanup(teardown);
    }
  });

  // ── Registration + teardown ─────────────────────────────────────────────────
  //
  // Setup work, not effect work: a Solid component body runs once, so there is no
  // double-invocation to defend against and nothing structural can change under the
  // registration — which is why React's version needs an effect with a dependency list and this
  // one does not.

  // Always registered, so a callback added to the options object stays reachable; the store's
  // own `runOnClose` is a no-op when there is nothing to call.
  store.setOnClose((result) => {
    return options.onClose?.(result);
  });

  dm.register(modalId, store, {
    modalType,
    nonModal: isNonModal,
    ...(options.onOpenRequest !== undefined && {
      // Returned, not swallowed: the manager awaits the handler, so an owner that validates
      // asynchronously still gets to refuse before `requestOpenAndWait` answers.
      onOpenRequest: (
        payload: unknown,
        request: Parameters<NonNullable<typeof options.onOpenRequest>>[1]
      ) => {
        return options.onOpenRequest?.(payload, request);
      },
    }),
  });

  onCleanup(() => {
    teardownModal(store, dm, modalId, getDialog());
  });

  // ── What the caller places ──────────────────────────────────────────────────

  const outlet = useModalOutletContext();

  let Modal: JSX.Element = placed;

  if (shouldPortal) {
    // **The one place the surface differs from React's, and it is the renderer's difference.**
    // React's `createPortal` produces a node the caller still has to render; a Solid modal owns
    // its element, so the binding mounts it here and `Modal` is `null`. Placing it anyway is
    // harmless, and neither an outlet nor a caller has to do anything for a portaled dialog to
    // appear — which is why there is no outlet registration on this branch.
    document.body.append(placed);
    onCleanup(() => {
      placed.remove();
    });
    Modal = null;
  } else if (outlet) {
    outlet.register(modalId, placed);
    onCleanup(() => {
      outlet.unregister(modalId);
    });
    Modal = null;
  }

  return {
    open,
    openAndWait,
    handle,
    action,
    Modal,
    dialogManager: dm,
    get isVisible() {
      return isVisible();
    },
    get isPreparing() {
      return isPreparing();
    },
    get hasRunningAction() {
      return hasRunningAction();
    },
    get error() {
      return currentError();
    },
  };
}
