// src/react/use-dialog.tsx
import {
  useEffect,
  useRef,
  useState,
  useSyncExternalStore,
  type CSSProperties,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { runDeclarationWindow } from '../actions/action-engine.js';
import { createActionFactory } from '../core/action-factory.js';
import type { RegisteredDialogId } from '../core/registry.js';
import type { RegisteredOptions, RegisteredReturn } from '../core/registered-types.js';
import {
  DIALOG_CONTENT_STYLE,
  dialogAttributes,
  createBackdropPressGuard,
} from '../core/dialog-props.js';
import { createDialogDirector } from '../core/dialog-director.js';
import {
  createDialogRuntime,
  resolveDialogOptions,
  resolvePortalHost,
  shouldDismissOnBackdropClick,
  teardownDialog,
} from '../core/dialog-runtime.js';
import {
  DEFAULT_DIALOG_ANIMATION,
  getDialogAnimationStyles,
  resolveAnimation,
} from '../utils/animation-utils.js';
import { answerDismiss } from '../utils/dismiss-gate.js';
import { useDialogManagerContext } from './dialog-manager-context.js';
import { useDialogOutletContext } from './dialog-outlet.js';
import type { GetDialog } from '../core/types.js';
import type { OpenRequestDispatch } from '../manager/dialog-manager.js';
import type { DialogAnimation, UseDialogOptions, UseDialogReturn } from './types.js';

/**
 * Core dialog hook that renders a native `<dialog>` with animation, backdrop handling and typed
 * close results. Actions are declared by being rendered: the `action` given to `render` names a
 * reason, binds a handler and returns its button's props, in one expression. **What is React's
 * here is the scheduling and nothing else** — every decision, and the order they are asked in, is
 * `core/`'s, `core/dialog-director.ts`'s in particular.
 *
 * @typeParam TData - Type of the close data payload. Defaults to `void`.
 * @typeParam TReason - The reasons this dialog closes with; declare a union
 * (`useDialog<Result, 'save' | 'cancel'>`) rather than take the `string` default. `'dismiss'` is
 * always among them — Escape, backdrop click, teardown — and is the one reason **no action may be
 * named**. See `DismissReason`.
 * @example
 * const { openAndWait, Dialog } = useDialog<void, 'ok'>({
 *   id: 'my-dialog',
 *   render: ({ action }) => <button {...action('ok')}>OK</button>,
 *   onClose: (result) => console.log(result.reason),
 * });
 */
/**
 * The registered door, first so a declared id is matched by it — whether the caller wrote the id
 * as a literal and let it infer, or named it as the one type argument. While `DialogRegistry` is
 * empty `RegisteredDialogId` is `never`, this overload is uninhabitable, and every call falls
 * through to the one below, which is the signature this hook has always had.
 */
export function useDialog<TId extends RegisteredDialogId>(
  options: RegisteredOptions<TId, CSSProperties, ReactNode>
): RegisteredReturn<TId, ReactNode>;
export function useDialog<TData = void, TReason extends string = string>(
  options: UseDialogOptions<TData, TReason>
): UseDialogReturn<TData, TReason>;
export function useDialog<TData = void, TReason extends string = string>(
  options: UseDialogOptions<TData, TReason>
): UseDialogReturn<TData, TReason> {
  const {
    id: dialogId,
    render,
    animation: animationProp,
    style: styleProp,
    onKeyDown,
    prepare,
    onError,
    onOpenRequest,
    onClose,
    restoreFocusTo,
    onDismissRequest,
    ariaLabel,
    ariaLabelledBy,
    ariaDescribedBy,
    role,
    portal,
  } = options;

  // The defaults and the variant narrowing, from the one place both bindings read them.
  const {
    isNonModal,
    isPortaled,
    dismissOnBackdropClick,
    dismissOnClickOutside,
    dismissWhilePreparing,
    dismissKey,
    containFocus,
    template,
    placement,
  } = resolveDialogOptions(options);

  const manager = useDialogManagerContext();

  // Built once: fresh doors each render would force consumers through refs and defeat memoization
  // inside `render`, and React Compiler cannot hoist them — they capture a value it treats opaque.
  const [init] = useState(() => {
    // A plain box behind a callback ref, not `useRef`: the runtime is handed `getDialog` while the
    // component renders, and a closure over a React ref crossing that call is what the compiler
    // reads as a render-phase ref access. Stable identity, so React never re-invokes the callback.
    const box: { element: HTMLDialogElement | null } = { element: null };
    const getDialog: GetDialog = () => {
      return box.element;
    };
    const setDialog = (node: HTMLDialogElement | null) => {
      box.element = node;
    };

    const runtime = createDialogRuntime<TData, TReason>(dialogId, getDialog);

    return { ...runtime, backdropPress: createBackdropPressGuard(), getDialog, setDialog };
  });
  const { backdropPress, store, engine, getDialog, setDialog, open, openAndWait, handle } = init;

  // Kept likewise: the director remembers each step's attachment and where opening focus landed.
  const [director] = useState(() => {
    return createDialogDirector({ store, getDialog, dialogId, manager, engine });
  });

  // The same reader serves the server: both stores are in-memory and DOM-free, so a server pass and
  // hydration's first pass read the identical freshly-closed dialog. Required rather than optional —
  // `useSyncExternalStore` throws without a third argument, taking the server render of any page
  // that mounts a dialog down with it.
  const snap = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getSnapshot);
  const actionSnap = useSyncExternalStore(engine.subscribe, engine.getSnapshot, engine.getSnapshot);

  // The only place an action is ever declared; built per render, over that render's snapshot.
  const action = createActionFactory(engine, () => {
    return actionSnap;
  });

  // Annotated, not inferred: un-annotated, the fallback and the caller's `DialogAnimation` stay a
  // union, and `getDialogAnimationStyles` infers its style parameter from the first branch alone.
  const animation: DialogAnimation = animationProp ?? DEFAULT_DIALOG_ANIMATION;

  // The resolution the inline `transition` uses, so the exit's property and timeout match it.
  const { primaryProperty, exitDuration } = resolveAnimation(animation);

  // No deps array, so the store always holds the latest callbacks without a ref.
  useEffect(() => {
    store.setOnClose(onClose);
    store.setRestoreFocusTo(restoreFocusTo);
  });

  // No deps, so `prepare` and `onKeyDown` are never a render behind; no cleanup, because one would
  // tear the sequence down before every re-run and leave the director nothing to diff.
  useEffect(() => {
    director.sync({
      phase: snap.phase,
      isPreparing: snap.isPreparing,
      prepare,
      onError,
      onKeyDown,
      nonModal: isNonModal,
      primaryProperty,
      exitDuration,
      dismissKey,
      dismissWhilePreparing,
      onDismissRequest,
      containFocus,
      dismissOnClickOutside,
    });
  });

  // Declared first: React runs cleanups in declaration order, so listeners detach before unregister.
  useEffect(() => {
    return () => {
      director.destroy();
    };
  }, [director]);

  // Re-runs when `template` / `nonModal` change, because those change the rendered structure and a
  // native <dialog> cannot survive remounting into a different one while open — so the cleanup
  // unregisters *and* finalizes rather than orphaning it. Both callbacks below go through a ref:
  // one whose identity moves every render would re-register.
  const openRequestHandler = useRef(onOpenRequest);
  useEffect(() => {
    openRequestHandler.current = onOpenRequest;
  }, [onOpenRequest]);

  const errorHandler = useRef(onError);
  useEffect(() => {
    errorHandler.current = onError;
  }, [onError]);

  // A registration-time fact, hence a dependency: declaring one later means re-registering.
  const acceptsOpenRequests = onOpenRequest !== undefined;

  useEffect(() => {
    manager.register(dialogId, {
      store,
      template,
      nonModal: isNonModal,
      getDialog,
      ...(acceptsOpenRequests && {
        // Returned, not swallowed: the manager awaits it, so an owner that validates asynchronously
        // still refuses before `requestOpenAndWait` answers.
        onOpenRequest: (payload: unknown, request: OpenRequestDispatch) => {
          return openRequestHandler.current?.(payload, request);
        },
      }),
    });

    return () => {
      teardownDialog(store, {
        manager,
        dialogId,
        dialog: getDialog(),
        onError: (failure) => {
          errorHandler.current?.(failure);
        },
      });
    };
    // `isPortaled` is a dep the body never reads: like `nonModal`, it changes the structure.
  }, [acceptsOpenRequests, manager, getDialog, isNonModal, dialogId, template, isPortaled, store]);

  // Inline to satisfy React Compiler. The decision is `dialog-runtime.ts`'s and the answer is
  // `answerDismiss`'s — a controlled surface hears this door the way it hears the dismiss key. It
  // takes only a structural slice of the event, so React's synthetic one satisfies it unchanged.
  const handleBackdropClick = (event: React.MouseEvent<HTMLDialogElement>) => {
    const dialog = getDialog();
    if (!dialog) {
      return;
    }
    if (
      shouldDismissOnBackdropClick(event, {
        pressedOnBackdrop: backdropPress.take(),
        dialog,
        store,
        engine,
        isNonModal,
        dismissOnBackdropClick,
        dismissWhilePreparing,
      })
    ) {
      answerDismiss(store, { request: onDismissRequest, cause: 'backdrop-click' });
    }
  };

  const outlet = useDialogOutletContext();

  // A declaration window, so the engine learns which actions this pass drew: re-declaring rather
  // than accumulating stops a hotkey outliving its button and suppressing the dismiss key.
  const renderContent = () => {
    return runDeclarationWindow(engine, () => {
      return render({
        isPreparing: snap.isPreparing,
        phase: snap.phase,
        handle,
        action,
        hasRunningAction: actionSnap.hasRunningAction,
        error: actionSnap.error,
      });
    });
  };

  const dialogElement = (
    <dialog
      ref={setDialog}
      // Styling surface and accessible name, from the table both bindings read (`dialog-props.ts`).
      {...dialogAttributes({
        dialogId,
        nonModal: isNonModal,
        isPreparing: snap.isPreparing,
        ariaLabel,
        ariaLabelledBy,
        ariaDescribedBy,
        role,
      })}
      onClick={handleBackdropClick}
      onPointerDown={backdropPress.press}
      style={getDialogAnimationStyles(snap.phase, { animation, customStyle: styleProp, placement })}
    >
      {/* Content wrapper — see `DIALOG_CONTENT_STYLE`, which both bindings read. */}
      <div style={DIALOG_CONTENT_STYLE}>{snap.phase !== 'closed' && renderContent()}</div>
    </dialog>
  );

  let dialogNode: ReactNode;

  // Asked at placement rather than at hook time, so a host mounted by then is found, and guarded on
  // `isPortaled` because the *argument* is the problem: `document.body` on a server pass throws
  // where this binding otherwise renders a closed `<dialog>` with no DOM in scope.
  const [portalEra, setPortalEra] = useState(() => {
    return { isPortaled, host: isPortaled ? resolvePortalHost(portal, document.body) : null };
  });
  // An era, so the host is re-read only when `portal` flips between portaled and not. Re-reading it
  // every render strands an open dialog: a container of a different identity makes React mount a
  // *fresh*, closed `<dialog>`, which `syncOpenSequence` will not show again outside `'opening'`.
  if (portalEra.isPortaled !== isPortaled) {
    setPortalEra({
      isPortaled,
      host: isPortaled ? resolvePortalHost(portal, document.body) : null,
    });
  }
  const portalHost = portalEra.isPortaled === isPortaled ? portalEra.host : null;

  if (portalHost) {
    dialogNode = createPortal(dialogElement, portalHost);
  } else if (placement.host) {
    // The dialog's `absolute` positioning resolves against this host (closest positioned ancestor
    // wins), immune to transforms above, and it fills its parent so a slide anchors to that region.
    dialogNode = (
      <div data-dialog-container={dialogId} style={placement.host}>
        {dialogElement}
      </div>
    );
  } else {
    dialogNode = dialogElement;
  }

  // No cleanup: the <dialog> is always mounted, so `dialogNode` is never null and unmount is the
  // effect below. Passive, not layout — measured, the frame a layout effect would buy does not
  // exist, the outlet's re-render being a cascade either way. Bounded by the paint-timing test.
  useEffect(() => {
    if (!outlet) {
      return;
    }
    outlet.register(dialogId, dialogNode);
  });

  // Unmount-only: the outlet/dialogId identities are stable in practice.
  useEffect(() => {
    if (!outlet) {
      return;
    }
    return () => {
      outlet.unregister(dialogId);
    };
  }, [dialogId, outlet]);

  const Dialog: ReactNode = outlet ? null : dialogNode;

  return {
    open,
    isVisible: snap.phase !== 'closed',
    phase: snap.phase,
    isPreparing: snap.isPreparing,
    Dialog,
    openAndWait,
    handle,
    action,
    hasRunningAction: actionSnap.hasRunningAction,
    error: actionSnap.error,
    dialogManager: manager,
  };
}

// src/solid/use-dialog.ts
import { createEffect, createMemo, createRenderEffect, getOwner, onCleanup } from 'solid-js';
import { insert } from 'solid-js/web';
import type { JSX } from 'solid-js';
import type { RegisteredDialogId } from '../core/registry.js';
import type { RegisteredOptions, RegisteredReturn } from '../core/registered-types.js';
import { runDeclarationWindow } from '../actions/action-engine.js';
import { createActionFactory } from '../core/action-factory.js';
import {
  DIALOG_CONTENT_STYLE,
  dialogAttributes,
  setDialogAttributes,
  createBackdropPressGuard,
} from '../core/dialog-props.js';
import { createDialogDirector } from '../core/dialog-director.js';
import {
  createDialogRuntime,
  resolveDialogOptions,
  resolvePortalHost,
  shouldDismissOnBackdropClick,
  teardownDialog,
} from '../core/dialog-runtime.js';
import { applyStyle } from '../core/style.js';
import {
  DEFAULT_DIALOG_ANIMATION,
  getDialogAnimationStyles,
  resolveAnimation,
} from '../utils/animation-utils.js';
import { answerDismiss } from '../utils/dismiss-gate.js';
import { useDialogManagerContext } from './dialog-manager-context.js';
import { fromStore } from './from-store.js';
import { useDialogOutletContext } from './dialog-outlet.js';
import type { DialogStyle } from '../core/style.js';
import type { GetDialog, DialogRenderArgs } from '../core/types.js';
import type { DialogAnimation, UseDialogOptions, UseDialogReturn } from './types.js';

/**
 * `umbra/solid`'s core hook — the same `useDialog` as React's, over the same core.
 *
 * **Written without JSX, on purpose**: Solid's JSX is a compile step (`babel-preset-solid`), and
 * requiring it to build *the library* would put a second toolchain in the way. So the `<dialog>`
 * is built with `document.createElement` and Solid's own `insert`, which is what compiled JSX
 * emits anyway; consumers write ordinary JSX and only a `JSX.Element` crosses the boundary.
 *
 * Two differences from React's binding, both the renderer's: nothing re-renders, and an action
 * un-declares itself — a button removed by its own `<Show>` calls `engine.undeclare` from
 * `onCleanup`, without which its hotkey lives on and `hasActions()`, which decides whether a
 * backdrop click dismisses, never returns to false.
 *
 * @typeParam TData - Type of the close data payload. Defaults to `void`.
 * @typeParam TReason - The reasons this dialog closes with. Declare them.
 */
/**
 * The registered door, first so a declared id is matched by it — whether the caller wrote the id as
 * a literal and let it infer, or named it as the one type argument. While `DialogRegistry` is empty
 * `RegisteredDialogId` is `never`, this overload is uninhabitable, and every call falls through to
 * the one below, which is the signature this hook has always had.
 */
export function useDialog<TId extends RegisteredDialogId>(
  options: RegisteredOptions<TId, DialogStyle, JSX.Element>
): RegisteredReturn<TId, JSX.Element>;
export function useDialog<TData = void, TReason extends string = string>(
  options: UseDialogOptions<TData, TReason>
): UseDialogReturn<TData, TReason>;
export function useDialog<TData = void, TReason extends string = string>(
  options: UseDialogOptions<TData, TReason>
): UseDialogReturn<TData, TReason> {
  const dialogId = options.id;

  // The defaults and the variant narrowing, from the one place both bindings read them.
  const {
    isNonModal,
    isPortaled,
    dismissOnBackdropClick,
    dismissOnClickOutside,
    dismissWhilePreparing,
    dismissKey,
    containFocus,
    template,
    placement,
  } = resolveDialogOptions(options);

  // Annotated for the reason React's binding gives.
  const animation: DialogAnimation = options.animation ?? DEFAULT_DIALOG_ANIMATION;

  const manager = useDialogManagerContext();

  // Built here rather than handed to a renderer, so `getDialog` closes over it — no ref dance.
  const dialog = document.createElement('dialog');
  const getDialog: GetDialog = () => {
    return dialog;
  };

  const { store, engine, open, openAndWait, handle } = createDialogRuntime<TData, TReason>(
    dialogId,
    getDialog
  );

  const snapshot = fromStore(store);
  const actionState = fromStore(engine);

  // A render effect, so the element is stamped at creation, before anything can insert or show it.
  // `aria-busy` is why it is an effect at all — the rest of the table is fixed.
  createRenderEffect(() => {
    setDialogAttributes(
      dialog,
      dialogAttributes({
        dialogId,
        nonModal: isNonModal,
        isPreparing: snapshot().isPreparing,
        ariaLabel: options.ariaLabel,
        ariaLabelledBy: options.ariaLabelledBy,
        ariaDescribedBy: options.ariaDescribedBy,
        role: options.role,
      })
    );
  });

  const content = document.createElement('div');
  applyStyle(content, { next: DIALOG_CONTENT_STYLE });
  dialog.append(content);

  // A render effect, so the exit/entrance state is written before `syncOpenSequence` shows it.
  let appliedStyle: DialogStyle | undefined;
  createRenderEffect(() => {
    appliedStyle = applyStyle(dialog, {
      next: getDialogAnimationStyles(snapshot().phase, {
        animation,
        customStyle: options.style,
        placement,
      }),
      previous: appliedStyle,
    });
  });

  // The dialog's `absolute` positioning resolves against this host, immune to a transform above.
  let placed: HTMLElement = dialog;
  if (placement.host) {
    const host = document.createElement('div');
    host.setAttribute('data-dialog-container', dialogId);
    applyStyle(host, { next: placement.host });
    host.append(dialog);
    placed = host;
  }

  const baseAction = createActionFactory(engine, actionState);

  // The core factory plus the expiry a fine-grained renderer owes it: the owner is whatever scope
  // drew the button, so one that disappears takes its declaration with it. `typeof baseAction`
  // stops a bare arrow dropping `isRunning` off the wrapper, which `binding-parity.test.ts` cannot
  // catch.
  const action: typeof baseAction = Object.assign(
    (...args: Parameters<typeof baseAction>) => {
      const props = baseAction(...args);
      if (getOwner()) {
        onCleanup(() => {
          engine.undeclare(args[0]);
        });
      }
      return props;
    },
    { isRunning: baseAction.isRunning }
  );

  const isPreparing = () => {
    return snapshot().isPreparing;
  };
  const hasRunningAction = () => {
    return actionState().hasRunningAction;
  };
  const currentError = () => {
    return actionState().error;
  };
  const isVisible = createMemo(() => {
    return snapshot().phase !== 'closed';
  });

  const renderArgs: DialogRenderArgs<TData, TReason> = {
    handle,
    action,
    get isPreparing() {
      return isPreparing();
    },
    get phase() {
      return snapshot().phase;
    },
    get hasRunningAction() {
      return hasRunningAction();
    },
    get error() {
      return currentError();
    },
  };

  // Keyed on visibility alone, not the whole snapshot: `isPreparing` reaches the content as a
  // getter, so a dialog that starts loading updates the part that reads it instead of redrawing.
  insert(content, () => {
    if (!isVisible()) {
      return null;
    }
    // The declaration window. Actions inside a `<Show>` run after it and declare themselves then,
    // which is why `declare` falls back to the live table and `undeclare` above retires them.
    return runDeclarationWindow(engine, () => {
      return options.render(renderArgs);
    });
  });

  const backdropPress = createBackdropPressGuard();
  dialog.addEventListener('pointerdown', (event: PointerEvent) => {
    backdropPress.press(event);
  });

  // The decision is `dialog-runtime.ts`'s — the same call React's binding makes from its `onClick`.
  dialog.addEventListener('click', (event: MouseEvent) => {
    if (
      shouldDismissOnBackdropClick(event, {
        pressedOnBackdrop: backdropPress.take(),
        dialog,
        store,
        engine,
        isNonModal,
        dismissOnBackdropClick,
        dismissWhilePreparing,
      })
    ) {
      // Read off `options` at the event rather than captured: this listener is attached once, and
      // the owner's handler is a prop like any other.
      answerDismiss(store, { request: options.onDismissRequest, cause: 'backdrop-click' });
    }
  });

  // One effect, and **no `onCleanup` inside it**: Solid runs an effect's cleanups before every
  // re-run, which would tear the sequence down each pass and leave the director nothing to diff.
  // Everything comes off in `destroy()`. It tracks the snapshot and the option getters the body
  // reads.
  const { primaryProperty, exitDuration } = resolveAnimation(animation);
  const director = createDialogDirector({ store, getDialog, dialogId, manager, engine });

  createEffect(() => {
    const snap = snapshot();
    director.sync({
      phase: snap.phase,
      isPreparing: snap.isPreparing,
      prepare: options.prepare,
      onError: options.onError,
      onKeyDown: options.onKeyDown,
      nonModal: isNonModal,
      primaryProperty,
      exitDuration,
      dismissKey,
      dismissWhilePreparing,
      onDismissRequest: options.onDismissRequest,
      containFocus,
      dismissOnClickOutside,
    });
  });

  // Setup, not effect work: a Solid body runs once, so nothing structural changes under the
  // registration — which is why React's needs a dependency list. Always registered, so a callback
  // added later stays reachable; `runOnClose` no-ops when there is none.
  store.setOnClose((result) => {
    return options.onClose?.(result);
  });

  store.setRestoreFocusTo((result) => {
    return options.restoreFocusTo?.(result);
  });

  manager.register(dialogId, {
    store,
    template,
    nonModal: isNonModal,
    getDialog,
    ...(options.onOpenRequest !== undefined && {
      // Returned, not swallowed — the manager awaits it, so an async validation can still refuse.
      onOpenRequest: (
        payload: unknown,
        request: Parameters<NonNullable<typeof options.onOpenRequest>>[1]
      ) => {
        return options.onOpenRequest?.(payload, request);
      },
    }),
  });

  onCleanup(() => {
    // One cleanup rather than two: Solid runs an owner's cleanups in reverse registration order,
    // so a pair would read as the opposite of what it does. Detachments first, as in React.
    director.destroy();
    teardownDialog(store, { manager, dialogId, dialog: getDialog(), onError: options.onError });
  });

  const outlet = useDialogOutletContext();

  let Dialog: JSX.Element = placed;

  if (isPortaled) {
    // The one place the surface differs from React's: a Solid dialog owns its element, so the
    // binding mounts it and `Dialog` is `null`. Resolved once: this branch mounts the node itself
    // and runs exactly once, so a moving getter has nothing left to move.
    const host = resolvePortalHost(options.portal, document.body) ?? document.body;
    host.append(placed);
    onCleanup(() => {
      placed.remove();
    });
    Dialog = null;
  } else if (outlet) {
    outlet.register(dialogId, placed);
    onCleanup(() => {
      outlet.unregister(dialogId);
    });
    Dialog = null;
  }

  return {
    open,
    openAndWait,
    handle,
    action,
    Dialog,
    dialogManager: manager,
    get isVisible() {
      return isVisible();
    },
    get phase() {
      return snapshot().phase;
    },
    get isPreparing() {
      return isPreparing();
    },
    get hasRunningAction() {
      return hasRunningAction();
    },
    get error() {
      return currentError();
    },
  };
}
