// src/react/use-lookup.ts
import { useSyncExternalStore } from 'react';
import { useDialogManagerContext } from './dialog-manager-context.js';
import type { ModalInfo } from '../manager/types.js';

/**
 * Reactive hook for querying a single modal's state.
 *
 * Returns `ModalInfo` that updates whenever any modal opens or closes.
 * Uses `useSyncExternalStore` for tear-free reads. For open modals,
 * the result is a stable reference from the snapshot; for closed or
 * unregistered modals, the imperative `lookup(id)` provides the info.
 *
 * Automatically uses the nearest `DialogManagerProvider` instance, or
 * falls back to the static `dialogManager` singleton when no provider
 * is present.
 *
 * @example
 * function ModalStatus({ id }: { id: string }) {
 *   const info = useLookup(id);
 *   if (!info.exists) return <span>Not registered</span>;
 *   return <span>{info.isVisible ? 'Open' : 'Closed'}</span>;
 * }
 */
export function useLookup(id: string): ModalInfo {
  const dm = useDialogManagerContext();
  const snapshot = useSyncExternalStore(dm.subscribeSnapshot, dm.getSnapshot);

  // Linear scan — n is always tiny (1-3 open modals)
  const openModal = snapshot.openDialogs.find((d) => {
    return d.id === id;
  });
  if (openModal) {
    return openModal;
  }

  // Closed or unregistered — derive from imperative lookup
  return dm.lookup(id);
}

// src/solid/use-lookup.ts
import type { Accessor } from 'solid-js';
import { useDialogManagerContext } from './dialog-manager-context.js';
import { fromStore } from './from-store.js';
import type { ModalInfo } from '../manager/types.js';

/**
 * One modal's live state.
 *
 * **Returns an accessor, and that is forced rather than chosen.** `ModalInfo` is a discriminated
 * union — `info.exists` narrows it — and a union cannot be handed back as one object of getters
 * without flattening the discriminant away, which would cost exactly the narrowing the type
 * exists for. So this one is `info()`, while {@link useDialogManager} next door is not.
 *
 * @example
 * const info = useLookup('settings');
 * const label = () => {
 *   return info().exists && info().isVisible ? 'Open' : 'Closed';
 * };
 */
export function useLookup(id: string): Accessor<ModalInfo> {
  const manager = useDialogManagerContext();
  const snapshot = fromStore({
    subscribe: manager.subscribeSnapshot,
    getSnapshot: manager.getSnapshot,
  });

  return () => {
    // Linear scan — n is always tiny (1-3 open modals)
    const openModal = snapshot().openDialogs.find((d) => {
      return d.id === id;
    });
    if (openModal) {
      return openModal;
    }

    // Closed or unregistered — derive from imperative lookup
    return manager.lookup(id);
  };
}
