// src/solid/modal-outlet.ts
import {
  For,
  createComponent,
  createContext,
  createMemo,
  createSignal,
  useContext,
} from 'solid-js';
import type { JSX } from 'solid-js';
import { createLogger } from '../utils/logger.js';

const log = createLogger('outlet');

type ModalOutletContextValue = {
  readonly register: (id: string, node: JSX.Element) => void;
  readonly unregister: (id: string) => void;
};

const ModalOutletContext = createContext<ModalOutletContextValue | null>(null);

/**
 * Read the nearest outlet context. Returns `null` when no `ModalOutlet` wraps the caller — in
 * that case `useModal` returns the dialog via `Modal` as usual.
 *
 * @internal Not part of the public API.
 */
export function useModalOutletContext(): ModalOutletContextValue | null {
  return useContext(ModalOutletContext);
}

/**
 * Scoped outlet that automatically renders modals from descendant `useModal` calls.
 *
 * Same contract as React's: when an outlet wraps a subtree, every `useModal` inside it registers
 * its dialog here instead of returning it via `Modal`, which becomes `null`. Outlets nest; the
 * nearest one wins.
 *
 * **It costs less here, and the reason is instructive.** React's outlet has to move a rendered
 * *node* through state, because a React element only exists while some component returns it — so
 * registration happens in an effect and every descendant re-render republishes. A Solid modal
 * owns a real DOM element from the moment it is created, so registration is a plain call during
 * setup and nothing re-runs when the modal's contents change. The outlet re-renders only when a
 * modal is added or removed.
 *
 * Usage is React's, unchanged — wrap a subtree (`<ModalOutlet><Dashboard /></ModalOutlet>`) and
 * stop placing `modal.Modal`. There is deliberately no `@example` here: this file's examples are
 * type-checked by a harness that compiles JSX as React's, and an imported *Solid* component
 * inside JSX cannot pass it. An example that could not be checked would be worth less than this
 * sentence; the checked one is on `umbra/react`'s `ModalOutlet`.
 */
export function ModalOutlet(props: { readonly children: JSX.Element }): JSX.Element {
  const [modals, setModals] = createSignal<ReadonlyMap<string, JSX.Element>>(new Map());

  const context: ModalOutletContextValue = {
    register(id, node) {
      setModals((current) => {
        if (current.has(id)) {
          return current;
        }
        log('Registering modal', { id });
        return new Map(current).set(id, node);
      });
    },
    unregister(id) {
      setModals((current) => {
        if (!current.has(id)) {
          return current;
        }
        log('Unregistering modal', { id });
        const next = new Map(current);
        next.delete(id);
        return next;
      });
    },
  };

  // The node references are stable for the life of a modal, so `For` reuses each row and only
  // does work when one is added or removed.
  const nodes = createMemo(() => {
    return [...modals().values()];
  });

  return createComponent(ModalOutletContext.Provider, {
    value: context,
    get children(): JSX.Element {
      // The children first, so descendants have registered by the time the list below is read;
      // then the registered dialogs.
      return [
        props.children,
        createComponent(For, {
          get each() {
            return nodes();
          },
          children: (node: JSX.Element) => {
            return node;
          },
        }),
      ];
    },
  });
}

// src/react/modal-outlet.tsx
import { createStore } from '../store/index.js';
import {
  Fragment,
  createContext,
  use,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from 'react';
import { createLogger } from '../utils/logger.js';

const log = createLogger('outlet');

type ModalOutletContextValue = {
  readonly register: (id: string, node: ReactNode) => void;
  readonly unregister: (id: string) => void;
};

const ModalOutletContext = createContext<ModalOutletContextValue | null>(null);

/**
 * The nearest outlet context, or `null` when none wraps the caller — then `useModal` returns the
 * dialog via `Modal` as usual.
 *
 * @internal Not part of the public API.
 */
export function useModalOutletContext(): ModalOutletContextValue | null {
  return use(ModalOutletContext);
}

// The outlet holds rendered *nodes* rather than a DOM anchor to portal into, because a React
// element only renders while some component returns it and the consumer must never write
// `{Modal}`. Two inherent costs: registration is an effect (mutating an external store during
// render breaks concurrent rendering), so content lands one commit behind its owner — not a visible
// frame, see the paint-timing note in `use-modal.tsx` — and every descendant render republishes,
// re-rendering the outlet cheaply (`children` is unchanged, so React bails out). Two redesigns
// rejected: a portal-anchor outlet removes both but reintroduces `{Modal}`; a per-modal host
// component would confine the second, for no measurable win.

type OutletSnapshot = {
  readonly modals: ReadonlyMap<string, ReactNode>;
};

function createOutletStore() {
  // Annotated, not type arguments — two of those match `createStore`'s generic overload by arity.
  const initial: OutletSnapshot = { modals: new Map() };

  return createStore(initial, {
    builder: ({ set }): OutletStoreMethods => {
      const modals = new Map<string, ReactNode>();

      return {
        register(id: string, node: ReactNode): void {
          const isNew = !modals.has(id);
          if (isNew) {
            log('Registering modal', { id });
          }
          modals.set(id, node);
          set({ modals: new Map(modals) });
        },

        unregister(id: string): void {
          if (modals.delete(id)) {
            log('Unregistering modal', { id });
            set({ modals: new Map(modals) });
          }
        },
      };
    },
  });
}

type OutletStoreMethods = {
  register(id: string, node: ReactNode): void;
  unregister(id: string): void;
};

/**
 * Scoped outlet that renders the dialogs of every descendant `useModal` call, so nothing has to
 * place `{modal.Modal}` in JSX. Inside one a modal registers here instead and its `Modal` becomes
 * `null` — destructuring still works, it renders nothing. Outlets nest: the nearest wins.
 * @example
 * ```tsx
 * function App() {
 *   // Modals opened anywhere below render here.
 *   return (
 *     <ModalOutlet>
 *       <Dashboard />
 *     </ModalOutlet>
 *   );
 * }
 *
 * function Dashboard() {
 *   const { open } = useModal({ id: 'info', render: () => <div>Hello</div> });
 *   // No need to render `Modal` — the outlet handles it.
 *   return (
 *     <button
 *       onClick={() => {
 *         void open();
 *       }}
 *     >
 *       Open
 *     </button>
 *   );
 * }
 * ```
 */
export function ModalOutlet({ children }: { readonly children: ReactNode }) {
  // Created once with the store so its identity is stable: a fresh context object per render would
  // re-render every descendant `useModal`, which re-registers, which is a loop.
  const [init] = useState(() => {
    const store = createOutletStore();
    const ctx: ModalOutletContextValue = {
      register: (id, node) => {
        store.register(id, node);
      },
      unregister: (id) => {
        store.unregister(id);
      },
    };
    return { store, ctx };
  });

  const snap = useSyncExternalStore(init.store.subscribe, init.store.getSnapshot);

  return (
    <ModalOutletContext value={init.ctx}>
      {children}
      {Array.from(snap.modals.entries(), ([id, node]) => {
        return <Fragment key={id}>{node}</Fragment>;
      })}
    </ModalOutletContext>
  );
}
